services:
  postgres:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: ${POSTGRES_IMAGE_NAME}
    restart: "no"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - .postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: ${RABBITMQ_IMAGE_NAME}
    container_name: ${RABBITMQ_CONTAINER_NAME}
    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_UI_PORT}:15672
    volumes:
      - .rabbitmq_data:/var/lib/rabbitmq
volumes:
  rabbitmq_data:
    name: .rabbitmq_data
  postgres_data:
    name: .postgres_data
